version: '3.8'

services:
  ppt_mcp_server:
    image: ppt_mcp_server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppt_mcp_server
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "ppt_mcp_server.py", "--transport", "http", "--port", "8000"]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./public:/app/public
      - ./tools:/app/tools
      - ./utils:/app/utils
      # Montages fichier à fichier (assure-toi que ces fichiers existent sur l’hôte !)
      - ./slide_layout_templates.json:/app/slide_layout_templates.json
      - ./mcp-config.json:/app/mcp-config.json
