# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Dépendances système minimales (libffi pour certaines libs python)
RUN apk add --no-cache gcc musl-dev libffi-dev

# Répertoire de travail
WORKDIR /app

# Copie du code et des assets (y compris les JSON)
COPY . .

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Var runtime utile pour des logs sans buffering
ENV PYTHONUNBUFFERED=1

# Expose (utile côté documentation/outils)
EXPOSE 8000

# Démarrage par défaut en HTTP sur 8000
ENTRYPOINT ["python", "ppt_mcp_server.py"]
CMD ["--transport", "http", "--port", "8000"]
