version: '3.8'
services:
  ppt_mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppt_mcp_server:latest
    container_name: ppt_mcp_server
    ports:
      - "8000:8000"
    restart: unless-stopped

    # ⚠️ Ici on ne met QUE les arguments (pas "python ppt_mcp_server.py")
    command: ["--transport","sse","--port","8000"]

    environment:
      - PYTHONUNBUFFERED=1

    # Optionnel : healthcheck seulement si ton serveur répond sur /
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
